apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: devopseasylearning/banga-db:v0.0.1
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: my-secret-pw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-rolebinding
subjects:
- kind: ServiceAccount
  name: db-serviceaccount
roleRef:
  kind: Role
  name: db-role
  apiGroup: rbac.authorization.k8s.io

