apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: devopseasylearning/banga-weather:v0.0.1
        env:
          - name: APIKEY
            value: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weather-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weather-rolebinding
subjects:
- kind: ServiceAccount
  name: weather-serviceaccount
roleRef:
  kind: Role
  name: weather-role
  apiGroup: rbac.authorization.k8s.io

