apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: devopseasylearning/banga-ui:v0.0.1
        env:
          - name: AUTH_HOST
            value: auth
          - name: AUTH_PORT
            value: "8080"
          - name: WEATHER_HOST
            value: weather
          - name: WEATHER_PORT
            value: "5000"
          - name: REDIS_USER
            value: redis
          - name: REDIS_PASSWORD
            value: redis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ui-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui-rolebinding
subjects:
- kind: ServiceAccount
  name: ui-serviceaccount
roleRef:
  kind: Role
  name: ui-role
  apiGroup: rbac.authorization.k8s.io

